"""empty message

Revision ID: 5ef4f4a6b8b7
Revises: 
Create Date: 2023-03-06 15:42:30.588468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef4f4a6b8b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_tags', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
